application:
  actions: actions
  runtimeManifest:
    packages:
      mmsg_test:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              SUBSCRIPTION_KEY : $SUBSCRIPTION_KEY
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: false
          SMTP:
            function: actions/SMTP/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              SMTP_PASSWORD : $SMTP_PASSWORD
              SMTP_USER : $SMTP_USER
              SMTP_HOST : $SMTP_HOST
              SMTP_PORT : $SMTP_PORT
              EMAIL_TO : $EMAIL_TO
              EMAIL_CC : $EMAIL_CC
              EMAIL_BCC : $EMAIL_BCC
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: false
          captcha:
            function: actions/captcha/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              SUBSCRIPTION_KEY : $SUBSCRIPTION_KEY
              RECAPTCHA_SECRET_KEY : $RECAPTCHA_SECRET_KEY
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: false