name: AIO App CI

on:
  push:
    branches:
      - ioruntime
jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['20']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{secrets.AIO_RUNTIME_NAMESPACE}}
          AIO_RUNTIME_APIHOST: ${{secrets.AIO_RUNTIME_APIHOST}}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: build
      - name: Deploy
        env:
          AIO_RUNTIME_NAMESPACE: ${{secrets.AIO_RUNTIME_NAMESPACE}}
          AIO_RUNTIME_APIHOST: ${{secrets.AIO_RUNTIME_APIHOST}}
          SMTP_USER: ${{secrets.SMTP_USER}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}
          SUBSCRIPTION_KEY: ${{secrets.SUBSCRIPTION_KEY}}
          EMAIL_TO: ${{secrets.EMAIL_TO}}
          EMAIL_CC: ${{secrets.EMAIL_CC}}
          EMAIL_BCC: ${{secrets.EMAIL_BCC}}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: deploy
          noPublish: true
