const data = [
  {
    offerId: 'offer_1',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: '20i M sports 8 SP Auto Steptronic Sports 2D couple 2.0L G22',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$45,540',
    weeklyPriceInfo: '$320',
    isButtonExists: true,
    type: 'petrol',
    isCheckbox: true,
    path: '/vehicle-offers/bmw',
    isEV: false,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_2',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Corolla Hybrid 1.8L CVT 5D Hatchback',
    year: 2023,
    modelName: 'toyota',
    isFeatures: true,
    price: '$35,540',
    weeklyPriceInfo: '$254',
    isButtonExists: true,
    type: 'ev',
    isCheckbox: true,
    path: '/vehicle-offers/toyota',
    isEV: true,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_3',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Civic 1.5L Turbo 6MT 4D Sedan',
    year: 2022,
    modelName: 'honda',
    isFeatures: true,
    price: '$25,540',
    weeklyPriceInfo: '$180',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/honda',
    isEV: false,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_4',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Mustang GT 5.0L V8 10AT 2D Coupe',
    year: 2021,
    modelName: 'ford',
    isFeatures: true,
    price: '$55,940',
    weeklyPriceInfo: '$400',
    isButtonExists: true,
    type: 'petrol',
    isCheckbox: true,
    path: '/vehicle-offers/ford',
    isEV: false,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_5',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'i3 Electric 125kW 1AT 5D Hatchback',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$55,540',
    weeklyPriceInfo: '$380',
    isButtonExists: true,
    type: 'ev',
    isCheckbox: true,
    path: '/vehicle-offers/bmw',
    isEV: true,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_6',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Yaris 1.5L Hybrid 5D Hatchback',
    year: 2023,
    modelName: 'toyota',
    isFeatures: true,
    price: '$28,540',
    weeklyPriceInfo: '$200',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/toyota',
    isEV: false,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_7',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Accord 2.0L Turbo 10AT 4D Sedan',
    year: 2022,
    modelName: 'honda',
    isFeatures: true,
    price: '$32,540',
    weeklyPriceInfo: '$230',
    isButtonExists: true,
    type: 'petrol',
    isCheckbox: true,
    path: '/vehicle-offers/honda',
    isEV: false,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_8',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'F-150 Lightning Electric 4D Pickup',
    year: 2021,
    modelName: 'ford',
    isFeatures: true,
    price: '$60,000',
    weeklyPriceInfo: '$420',
    isButtonExists: true,
    type: 'ev',
    isCheckbox: true,
    path: '/vehicle-offers/ford',
    isEV: true,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_9',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'X1 xDrive28i 2.0L Turbo 8AT 5D SUV',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$47,540',
    weeklyPriceInfo: '$330',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/bmw',
    isEV: false,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_10',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Camry 2.5L Hybrid 8AT 4D Sedan',
    year: 2023,
    modelName: 'toyota',
    isFeatures: true,
    price: '$33,540',
    weeklyPriceInfo: '$240',
    isButtonExists: true,
    type: 'petrol',
    isCheckbox: true,
    path: '/vehicle-offers/toyota',
    isEV: false,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_11',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Insight 1.5L Hybrid 5D Hatchback',
    year: 2022,
    modelName: 'honda',
    isFeatures: true,
    price: '$29,540',
    weeklyPriceInfo: '$210',
    isButtonExists: true,
    type: 'ev',
    isCheckbox: true,
    path: '/vehicle-offers/honda',
    isEV: true,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_12',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: 'Escape 2.0L Turbo 8AT 5D SUV',
    year: 2021,
    modelName: 'ford',
    isFeatures: true,
    price: '$31,540',
    weeklyPriceInfo: '$220',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/ford',
    isEV: false,
    isOlyDeal: false,
  },
];

export default data;
