const data = [
  {
    offerId: 'offer_1',
    img: '/content/dam/oly/images/BYD Seal_Premium.png',
    carDescription: '20i M sports 8 SP Auto Steptronic Sports 2D couple 2.0L G22',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$35,540',
    weeklyPriceInfo: '$254',
    isButtonExists: true,
    type: 'petrol',
    isCheckbox: true,
    path: '/vehicle-offers/volvocx40',
    isEV: true,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_2',
    img: '/content/dam/oly/img_car.png',
    carDescription: '20i M sports 8 SP Auto Steptronic Sports 2D couple 2.0L G22',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$35,540',
    weeklyPriceInfo: '$254',
    isButtonExists: true,
    type: 'ev',
    isCheckbox: true,
    path: '/vehicle-offers/volvocx40',
    isEV: false,
    isOlyDeal: true,
  },
  {
    offerId: 'offer_3',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: '20i M sports 8 SP Auto Steptronic Sports 2D couple 2.0L G22',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$35,540',
    weeklyPriceInfo: '$254',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/volvocx40',
    isEV: true,
    isOlyDeal: false,
  },
  {
    offerId: 'offer_4',
    img: '/content/dam/oly/images/tesla.jpeg',
    carDescription: '20i M sports 8 SP Auto Steptronic Sports 2D couple 2.0L G22',
    year: 2024,
    modelName: 'bmw',
    isFeatures: true,
    price: '$35,940',
    weeklyPriceInfo: '$258',
    isButtonExists: true,
    type: 'hatchback',
    isCheckbox: true,
    path: '/vehicle-offers/volvocx40',
    isEV: false,
    isOlyDeal: false,
  },
];

export default data;
