name: AIO App CI

on:
  push:
    branches:
      - ioruntime
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['20']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd mmsg_test
          npm install

      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          version: 10.x.x

      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{secrets.AIO_RUNTIME_NAMESPACE}}
          AIO_RUNTIME_APIHOST: ${{secrets.AIO_RUNTIME_APIHOST}}
        run: |
          cd mmsg_test
          aio app build

      - name: Deploy
        env:
          AIO_RUNTIME_NAMESPACE: ${{secrets.AIO_RUNTIME_NAMESPACE}}
          AIO_RUNTIME_AUTH: ${{secrets.AIO_RUNTIME_AUTH}}
          AIO_RUNTIME_APIHOST: ${{secrets.AIO_RUNTIME_APIHOST}}
          SMTP_USER: ${{secrets.SMTP_USER}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}
          SUBSCRIPTION_KEY: ${{secrets.SUBSCRIPTION_KEY}}
          EMAIL_TO: ${{secrets.EMAIL_TO}}
          EMAIL_CC: ${{secrets.EMAIL_CC}}
          EMAIL_BCC: ${{secrets.EMAIL_BCC}}
        run: |
          cd mmsg_test
          aio app deploy --no-publish
